"""empty message

Revision ID: bab29d667e70
Revises: 
Create Date: 2023-08-08 20:17:58.259269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab29d667e70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=40), nullable=False),
    sa.Column('lastName', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('profileImage', sa.String(length=200), nullable=True),
    sa.Column('isClinician', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bookedvisits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitTime', sa.String(length=20), nullable=False),
    sa.Column('visitDate', sa.String(length=20), nullable=False),
    sa.Column('clinicianId', sa.Integer(), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinicianId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patientId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exerciseprescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('dailyFrequency', sa.Integer(), nullable=True),
    sa.Column('weeklyFrequency', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('clinicianId', sa.Integer(), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinicianId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patientId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('senderIsClinician', sa.Boolean(), nullable=False),
    sa.Column('clinicianId', sa.Integer(), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinicianId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patientId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patientlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('clinicianId', sa.Integer(), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinicianId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patientId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('exerciseData', sa.String(length=500), nullable=False),
    sa.Column('images', sa.String(length=500), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=250), nullable=False),
    sa.Column('holdTime', sa.Integer(), nullable=True),
    sa.Column('exercisePrescriptionId', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercisePrescriptionId'], ['exerciseprescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises')
    op.drop_table('patientlists')
    op.drop_table('messages')
    op.drop_table('exerciseprescriptions')
    op.drop_table('bookedvisits')
    op.drop_table('users')
    # ### end Alembic commands ###